"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Locale = "en" | "pl";
type Dict = Record<string, string>;

const dictionaries: Record<Locale, Dict> = {
  en: {
    nav_about: "About",
    nav_approach: "Approach",
    nav_services: "Services",
    nav_reviews: "Reviews",
    nav_faq: "FAQ",
    nav_contact: "Contact",
    hero_badge: "BACP & BPS accredited",
    hero_title: "Compassionate therapy for children and adults",
    hero_cta_primary: "Book a free intro call",
    hero_cta_secondary: "Learn more",
    hero_secure: "Secure video sessions",
    hero_international: "International clients",
    hero_terms: "Short & long-term",
    sec_glimpse: "A glimpse",
    sec_glimpse_title: "Therapy, thoughtfully presented",
    sec_about: "About",
    sec_about_title: "About Julia",
    sec_approach: "Approach",
    sec_approach_title: "Therapeutic Approach",
    sec_services: "Services",
    sec_services_title: "How I can help",
    sec_testimonials: "Testimonials",
    sec_testimonials_title: "What clients say",
    sec_availability: "Working together",
    sec_availability_title: "How it works",
    sec_faq: "FAQ",
    sec_faq_title: "Frequently asked",
    sec_contact: "Contact",
    sec_contact_title: "Get in touch",
    hero_intro: "UK-trained, integrative psychotherapist. Online sessions available worldwide, including the UK and Poland. Feel understood, supported, and safe — no topic is off-limits.",
    about_p1: "I am a UK-trained psychotherapist and counsellor, holding both undergraduate and postgraduate degrees in psychology and psychotherapy. My qualifications are accredited by the British Association for Counselling and Psychotherapy (BACP) and the British Psychological Society (BPS).",
    about_p2: "At the heart of my practice is the therapeutic relationship. I believe meaningful change begins when you feel truly heard, understood, and supported — and this is what I strive to offer in every session.",
    approach_intro: "I work from an integrative approach, tailoring therapy to the unique needs of each client. I offer both short-term and long-term therapy depending on your goals and preferences.",
    contact_intro: "Send a message to enquire about availability and booking. We’ll reply with suggested times or next steps.",
    services_adults_title: "Adults",
    services_adults_p1: "Anxiety & stress",
    services_adults_p2: "Depression & low mood",
    services_adults_p3: "Life transitions",
    services_children_title: "Children & Teens",
    services_children_p1: "Behaviour & emotions",
    services_children_p2: "School issues",
    services_children_p3: "Identity & self-esteem",
    services_trauma_title: "Trauma & PTSD",
    services_trauma_p1: "Stabilisation",
    services_trauma_p2: "Coping skills",
    services_trauma_p3: "Gentle, paced work",
    availability_online_title: "Online worldwide",
    availability_online_l1: "Secure video sessions across time zones",
    availability_online_l2: "Flexible scheduling for expatriates and families",
    availability_online_l3: "Available in English and Polish",
    availability_languages_title: "Languages & Approach",
    availability_languages_l1: "Sessions available in English and Polish",
    availability_languages_l2: "Culturally sensitive, trauma‑informed",
    availability_languages_l3: "Integrative: Person‑Centred, CBT, Gestalt, SFBT",
    availability_fees_title: "Scheduling & Fees",
    availability_fees_l1: "50‑minute sessions with flexible scheduling",
    availability_fees_l2: "Time zones accommodated (worldwide online)",
    availability_fees_l3: "Sliding‑scale options available on request",
    work_step1_title: "Intro call (free, 15 minutes)",
    work_step1_l1: "Clarify what brings you and your goals",
    work_step1_l2: "Outline approach, confidentiality, and boundaries",
    work_step1_l3: "Agree logistics: schedule, fees, questions",
    work_step2_title: "First session (50 minutes)",
    work_step2_l1: "Map concerns, history, and strengths; set focus",
    work_step2_l2: "Decide rhythm (weekly/fortnightly) and aims",
    work_step2_l3: "Check comfort and adapt style to you",
    work_step3_title: "Ongoing support",
    work_step3_l1: "Regular sessions with reviews every 4–6 weeks",
    work_step3_l2: "Practical tools: grounding, CBT reframing, emotion skills",
    work_step3_l3: "Thoughtful endings; open door to return",
    faq_q1: "How many sessions will I need?",
    faq_a1: "It depends on your goals. We can work briefly (6–8) or longer-term. We’ll decide together.",
    faq_q2: "Do you offer online therapy?",
    faq_a2: "Yes — secure video sessions are available. You’ll receive a private link before your appointment.",
    faq_q3: "Is everything confidential?",
    faq_a3: "Yes. I follow professional ethical standards and confidentiality, with clear limits explained at the start.",
    faq_q4: "Do you work with children?",
    faq_a4: "Yes, children and adolescents. Sessions are designed in an age-appropriate, supportive way.",
    gallery_caption1: "Adult therapy builds clarity, coping skills, and resilience for everyday life.",
    gallery_caption2: "Group therapy offers shared insight, encouragement, and a sense of belonging.",
    gallery_caption3: "Child therapy nurtures expression, safety, and healthy emotional development.",
    about_b1_title: "UK-trained",
    about_b1_desc: "MSc Psychotherapy & Counselling",
    about_b2_title: "Accredited",
    about_b2_desc: "BACP & BPS memberships",
    about_b3_title: "International",
    about_b3_desc: "UK, Poland (online)",
    about_b4_title: "All topics welcome",
    about_b4_desc: "Confidential & non-judgemental",
    approach_l1: "Person-Centred Therapy (Rogerian)",
    approach_l2: "Gestalt Therapy",
    approach_l3: "Cognitive Behavioural Therapy (CBT)",
    approach_l4: "Solution-Focused Brief Therapy (SFBT)",
    services_note: "Apprenticeship pathway: Reduced-fee sessions with closely supervised, early-career counsellors coming soon.",
    cta_title: "Ready to take the next step?",
    cta_desc: "Book a brief, no-pressure introductory call to chat through your needs and next steps.",
    cta_btn: "Book an intro call",
    cta_call: "Call now",
    contact_name_label: "Your name",
    contact_name_ph: "Jane Doe",
    contact_email_label: "Email",
    contact_email_ph: "you@example.com",
    contact_msg_label: "Your message",
    contact_msg_ph: "Briefly describe what you’d like support with.",
    contact_send_btn: "Send enquiry",
    contact_or_call: "or call directly",
  },
  pl: {
    nav_about: "O mnie",
    nav_approach: "Podejście",
    nav_services: "Usługi",
    nav_reviews: "Opinie",
    nav_faq: "FAQ",
    nav_contact: "Kontakt",
    hero_badge: "Akredytacja BACP i BPS",
    hero_title: "Wspierająca terapia dla dzieci i dorosłych",
    hero_cta_primary: "Umów bezpłatną rozmowę",
    hero_cta_secondary: "Dowiedz się więcej",
    hero_secure: "Bezpieczne sesje wideo",
    hero_international: "Klienci międzynarodowi",
    hero_terms: "Krótko- i długoterminowo",
    sec_glimpse: "Zobacz",
    sec_glimpse_title: "Terapia — uważnie i z troską",
    sec_about: "O mnie",
    sec_about_title: "O Julii",
    sec_approach: "Podejście",
    sec_approach_title: "Podejście terapeutyczne",
    sec_services: "Usługi",
    sec_services_title: "W czym mogę pomóc",
    sec_testimonials: "Opinie",
    sec_testimonials_title: "Co mówią klienci",
    sec_availability: "Współpraca",
    sec_availability_title: "Jak to wygląda",
    sec_faq: "FAQ",
    sec_faq_title: "Najczęstsze pytania",
    sec_contact: "Kontakt",
    sec_contact_title: "Skontaktuj się",
    hero_intro: "Brytyjskie wykształcenie i podejście integracyjne. Sesje online dostępne na całym świecie, w tym w Wielkiej Brytanii i Polsce. Poczuj się wysłuchany/a i bezpieczny/a — żaden temat nie jest tabu.",
    about_p1: "Jestem terapeutką i psychoterapeutką z wykształceniem w Wielkiej Brytanii. Ukończyłam studia licencjackie i magisterskie z psychologii i psychoterapii. Moje kwalifikacje akredytują BACP oraz BPS.",
    about_p2: "Relacja terapeutyczna jest sercem mojej praktyki. Wierzę, że zmiana zaczyna się wtedy, gdy czujesz się naprawdę usłyszany/a, zrozumiany/a i wspierany/a — to właśnie oferuję w każdej sesji.",
    approach_intro: "Pracuję w podejściu integracyjnym, dostosowując terapię do indywidualnych potrzeb. Oferuję pracę krótkoterminową i długoterminową, w zależności od Twoich celów.",
    contact_intro: "Napisz, aby zapytać o dostępność i umówić konsultację. Odpowiemy z propozycją terminów i dalszymi krokami.",
    services_adults_title: "Dorośli",
    services_adults_p1: "Lęk i stres",
    services_adults_p2: "Obniżony nastrój i depresja",
    services_adults_p3: "Zmiany życiowe",
    services_children_title: "Dzieci i młodzież",
    services_children_p1: "Emocje i zachowanie",
    services_children_p2: "Trudności szkolne",
    services_children_p3: "Tożsamość i samoocena",
    services_trauma_title: "Trauma i PTSD",
    services_trauma_p1: "Stabilizacja",
    services_trauma_p2: "Umiejętności radzenia sobie",
    services_trauma_p3: "Delikatna, stopniowa praca",
    availability_online_title: "Online — cały świat",
    availability_online_l1: "Bezpieczne sesje wideo w różnych strefach czasowych",
    availability_online_l2: "Elastyczne terminy dla ekspatów i rodzin",
    availability_online_l3: "Dostępne po angielsku i polsku",
    availability_languages_title: "Języki i podejście",
    availability_languages_l1: "Sesje po angielsku i polsku",
    availability_languages_l2: "Wrażliwość międzykulturowa, podejście traumasensytywne",
    availability_languages_l3: "Integracyjnie: Skoncentrowana na Osobie, CBT, Gestalt, SFBT",
    availability_fees_title: "Terminy i opłaty",
    availability_fees_l1: "Sesje 50‑minutowe, elastyczne grafiki",
    availability_fees_l2: "Uwzględniam różne strefy czasowe (online)",
    availability_fees_l3: "Możliwe zniżki/ulgowe stawki — zapytaj",
    work_step1_title: "Rozmowa wstępna (bezpł., 15 min)",
    work_step1_l1: "Doprecyzowanie potrzeb i celów",
    work_step1_l2: "Omówienie podejścia, poufności i granic",
    work_step1_l3: "Ustalenie logistyki: terminy, opłaty, pytania",
    work_step2_title: "Pierwsza sesja (50 min)",
    work_step2_l1: "Mapa trudności, historii i zasobów; ustalamy fokus",
    work_step2_l2: "Ustalamy rytm (co tydzień/co dwa) i cele",
    work_step2_l3: "Sprawdzamy komfort i dopasowujemy styl pracy",
    work_step3_title: "Dalsza praca",
    work_step3_l1: "Regularne sesje z przeglądem co 4–6 tygodni",
    work_step3_l2: "Praktyczne narzędzia: ugruntowanie, CBT, regulacja emocji",
    work_step3_l3: "Uważne domykanie; możliwość powrotu w przyszłości",
    faq_q1: "Ile sesji będę potrzebować?",
    faq_a1: "To zależy od Twoich celów. Możemy pracować krótko (6–8) lub długoterminowo — zdecydujemy wspólnie.",
    faq_q2: "Czy oferujesz terapię online?",
    faq_a2: "Tak — bezpieczne sesje wideo. Otrzymasz prywatny link przed spotkaniem.",
    faq_q3: "Czy wszystko jest poufne?",
    faq_a3: "Tak. Przestrzegam standardów etycznych i zasad poufności, z jasno określonymi wyjątkami.",
    faq_q4: "Czy pracujesz z dziećmi?",
    faq_a4: "Tak, z dziećmi i młodzieżą. Sesje są dostosowane do wieku i potrzeb.",
    gallery_caption1: "Terapia dorosłych buduje klarowność, strategie radzenia sobie i odporność w codzienności.",
    gallery_caption2: "Terapia grupowa daje wspólny wgląd, wsparcie i poczucie przynależności.",
    gallery_caption3: "Terapia dzieci wspiera ekspresję, bezpieczeństwo i zdrowy rozwój emocjonalny.",
    about_b1_title: "Wykształcenie w UK",
    about_b1_desc: "Mgr psychoterapii i counsellingu",
    about_b2_title: "Akredytacje",
    about_b2_desc: "Członkostwo BACP i BPS",
    about_b3_title: "Międzynarodowo",
    about_b3_desc: "UK, Polska (online)",
    about_b4_title: "Wszystkie tematy mile widziane",
    about_b4_desc: "Poufnie i bez oceniania",
    approach_l1: "Terapia Skoncentrowana na Osobie (Rogerian)",
    approach_l2: "Terapia Gestalt",
    approach_l3: "Terapia Poznawczo‑Behawioralna (CBT)",
    approach_l4: "Terapia Skupiona na Rozwiązaniach (SFBT)",
    services_note: "Ścieżka stażowa: Wkrótce tańsze sesje z terapeutami na początku drogi pod ścisłym nadzorem.",
    cta_title: "Gotowa/gotowy na kolejny krok?",
    cta_desc: "Umów krótką, bez zobowiązań rozmowę wstępną, aby omówić potrzeby i dalsze kroki.",
    cta_btn: "Umów rozmowę wstępną",
    cta_call: "Zadzwoń teraz",
    contact_name_label: "Twoje imię i nazwisko",
    contact_name_ph: "Jan Kowalski",
    contact_email_label: "E‑mail",
    contact_email_ph: "ty@przyklad.com",
    contact_msg_label: "Twoja wiadomość",
    contact_msg_ph: "Krótko opisz, w czym potrzebujesz wsparcia.",
    contact_send_btn: "Wyślij zapytanie",
    contact_or_call: "lub zadzwoń bezpośrednio",
  },
};

const LocaleCtx = createContext<{ lang: Locale; t: (k: string) => string; setLang: (l: Locale) => void } | null>(null);

export function useLocale() {
  const ctx = useContext(LocaleCtx);
  if (!ctx) throw new Error("useLocale must be used within <LocaleProvider>");
  return ctx;
}

export function LocaleProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Locale>("en");
  useEffect(() => {
    const saved = localStorage.getItem("lang");
    const supported: Locale[] = ["en", "pl"];
    if (saved && (supported as string[]).includes(saved)) setLang(saved as Locale);
    else if (saved && !(supported as string[]).includes(saved)) setLang("en");
  }, []);
  const t = useMemo(() => (key: string) => dictionaries[lang]?.[key] ?? dictionaries.en[key] ?? key, [lang]);
  const value = useMemo(() => ({ lang, setLang: (l: Locale) => { localStorage.setItem("lang", l); setLang(l); }, t }), [lang]);
  return <LocaleCtx.Provider value={value}>{children}</LocaleCtx.Provider>;
}

export function LanguageSwitcher() {
  const { lang, setLang } = useLocale();
  return (
    <select
      value={lang}
      onChange={(e) => setLang(e.target.value as Locale)}
      className="inline-flex h-9 items-center rounded-md border px-3 py-1.5 text-sm bg-white/70 dark:bg-gray-900/40"
      aria-label="Language selector"
    >
      <option value="en">🇬🇧 English</option>
      <option value="pl">🇵🇱 Polski</option>
    </select>
  );
}
